### ISSUE TITLE
get rdf from vocabs for visualisations

### ISSUE THREAD

**Issue by babslgam** [karl-kraus/legalkraus-static#18]
instead of using multiple vocabs api endpoints based on https://vocabs.acdh.oeaw.ac.at/rest/v1/legal_kraus/ i'm currently retrieving the whole vocabulary from https://vocabs.acdh.oeaw.ac.at/rest/v1/legal_kraus/data?format=application/rdf%2Bxml and processing it.

@csae8092 should we fetch it on build from vocabs (which makes it dependent on vocabs beeing reachable during build time) or store it in the data repo?

**Comment by csae8092** [comment]
please store it in the repo, who knows what might happen otherwise... Thank you!!!
