### ISSUE TITLE
certain referenced entities cannot be resolved

### ISSUE THREAD

**Issue by babslgam** [karl-kraus/legalkraus-static#20]
i.e. https://github.com/karl-kraus/legalkraus-archiv/blob/main/data/editions/D_000001-002-000.xml#L72
which is needed for displaying the address of the sender of the letter
i guess because pmb prefix is missing. 
needed a workaround in the old app should be fixed in the data for the new app.

**Comment by csae8092** [comment]
Thanks for spotting this. I'll try to fix this hopefully until tomorrow

**Comment by babslgam** [comment]
thanks. 
because i just encountered it:
also relevant here: https://github.com/karl-kraus/legalkraus-archiv/blob/main/data/editions/D_000002-009-001.xml#L83 because we render this info as well.

**Comment by babslgam** [comment]
and also here:
https://github.com/karl-kraus/legalkraus-archiv/blob/main/data/editions/D_000002-015-000.xml#L57
i guess every attribute value in the pattern ```#[0-9]+``` references an pmb entity, but didn't check.

**Comment by csae8092** [comment]
should be resolved with https://github.com/karl-kraus/legalkraus-static/pull/23
