### ISSUE TITLE
correct start and end date for a case should be stored in the cases tei file

### ISSUE THREAD

**Issue by babslgam** [karl-kraus/legalkraus-static#31]
since we want to get rid of cases_index.json, start and end date of a case should be integrated into the cases tei file. there were some issues regarding the correctness of the dates in cases_index.json caused by deriving them from some date in the referenced documents or something like that. 

correct dates should be curated by the projects data team.

**Comment by csae8092** [comment]
cases teis have now 
```xml
<profileDesc>
    <creation>
            <title>Zeitraum des Rechtsstreites</title>
            <origDate notBefore-iso="1935-07-12" notAfter-iso="1935-07-12"/>
    </creation>
    ...
</profileDesc>
```

cases without dates look like this:
```xml
<profileDesc>
    <creation>
            <title>Zeitraum des Rechtsstreites</title>
            <origDate>keine Datierung</origDate>
    </creation>
    ...
</profileDesc>
